[terminal.shell]
program = "/usr/local/bin/bash"

[font]
size = 16.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
style = "Regular"

[font.offset]
y = 14

[scrolling]
history = 50000

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.96
option_as_alt = "OnlyLeft"  # Or "OnlyLeft"/"OnlyRight" if you use one side

[window.padding]
x = 1
y = 1

[colors]
draw_bold_text_with_bright_colors = true

[general]
import = ["colors-green.toml"]
