# make sure you use skhd, otherwise forget about "Å‚"

after-startup-command = []

start-at-login = true

default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

on-focused-monitor-changed = []
on-focus-changed = []

automatically-unhide-macos-hidden-apps = false

[[on-window-detected]]
   if.app-id = "com.microsoft.edgemac"
   run = "move-node-to-workspace 1"

[[on-window-detected]]
   if.app-id = "com.microsoft.teams2"
   run = "move-node-to-workspace 3"

[[on-window-detected]]
   if.app-id = "com.microsoft.Outlook"
   run = "move-node-to-workspace 2"

[[on-window-detected]]
   if.app-id = "ru.keepcoder.Telegram"
   run = "move-node-to-workspace 3"

[[on-window-detected]]
   if.app-id = "coing.ClockifyDesktop"
   run = "move-node-to-workspace 5"

[[on-window-detected]]
   if.app-id = "com.brave.Browser"
   run = "move-node-to-workspace 1"

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 0
    inner.vertical =   0
    outer.left =       0
    outer.bottom =     0
    outer.top =        0
    outer.right =      0

[mode.main.binding]

    # All possible commands: https://nikitabobko.github.io/AeroSpace/commands

    cmd-shift-h = 'resize smart +50'
    cmd-shift-l = 'resize smart -50'
    cmd-shift-e = 'balance-sizes'
    cmd-shift-f = 'fullscreen'

    alt-tab = 'workspace-back-and-forth'
